from selenium.webdriver.common.by import By


add_exercise = (By.CSS_SELECTOR, 'a[href="/exercise/create/"]')
all_field_for_add_exercise = (By.XPATH, '//*[@id="object-form"]/div/div[2]/div[1]')
my_exercises_button = (By.CSS_SELECTOR, 'a[href="/profile/exercises/380/"]')
exericise_name = (By.ID, 'field_name_u')
mepa_1 = (By.CSS_SELECTOR, 'select[id="field_measure_1_id"]')
mepa_2 = (By.CSS_SELECTOR, 'select[id="field_measure_2_id"]')
category = (By.CSS_SELECTOR, 'span[class="select2-selection select2-selection--single"]')
category_back = (By.XPATH, '//*[@id="select2-field_category_id-result-0jr8-329"]')
description = (By.ID, 'field_content_u')
save = (By.CSS_SELECTOR, 'button[type="submit"]')
find_exercise = (By.CSS_SELECTOR, 'input[class="form-control input-sm"]')
exercise_added = (By. ID, 'id="DataTables_Table_0"')
login_button = (By.XPATH, '//*[@id="header"]/a[1]')
registr_button = (By.XPATH, '//*[@id="login-form"]/div[1]/div[4]/button')
password_field = (By.ID, 'password')
email_field = (By.ID, 'email')
value = (By.CSS_SELECTOR, 'input[class="select2-search__field"]')
select_value = (By.CSS_SELECTOR, 'select[id="field_category_id"]')
need_to_add_Name = (By.XPATH, '//*[@id="object-form"]/div/div[2]/div[2]/div/div')
info = (By.ID, 'DataTables_Table_0')
name_ex_1 = (By.ID, 'DataTables_Table_0_wrapper')
pop_up_massage_exercise = (By.CSS_SELECTOR, 'div[class="alert result alert-success hidden"]')
delete_button = (By.CSS_SELECTOR, 'a[href="javascript:{}"]')